POST http://localhost:8070/v1/administration
Accept: application/json
Content-Type: application/json

{
  "ci": "123332 lp",
  "firstName": "Kevin",
  "firstSurname": "Escobar",
  "secondSurname": "Escobar",
  "phone": "+591 72589386",
  "email": "kevin@gmail.com",
  "password": "kevin"
}

###

GET http://localhost:8070/v1/administration/sesion
Accept: application/json