GET http://localhost:8080/v1/contact
Accept: application/json

###
POST http://localhost:8080/v2/contact
Accept: application/json
Content-Type: application/json

{
  "driverId": 1,
  "administrationId":1 ,
  "accountNumber": 123321,
  "bank": "Banco Nacional",
  "accountType": "Caja de ahorros",
  "status": 1
}