POST http://localhost:8070/v1/driver
Accept: application/json
Content-Type: application/json

{
  "ci": "124248596 lp",
  "firstName": "Carlos",
  "firstSurname": "Aguilar",
  "secondSurname": "Quispe",
  "birthDate": "1996-11-10",
  "phone": "+591 68459315",
  "email": "carlosaguilar@gmail.com",
  "password": "aguilar",
  "number":"198B",
  "street":"Pisagua",
  "zone":"Norte",
  "city":"La Paz",
  "country":"Bolivia",
  "companyId": null
}

###

GET http://localhost:8070/v1/driver/2
Accept: application/json

###

PUT  http://localhost:8070/v1/driver
Accept: application/json
Content-Type: application/json

{
  "driverId": 3,
  "ci": "124248596 sc",
  "firstName": "Sebastian",
  "firstSurname": "Carrasco",
  "secondSurname": "Giraldez",
  "birthDate": "1974-01-17",
  "phone": "+591 77745812",
  "email": "carrasco@gmail.com",
  "password": "carrasco",
  "number":"198B",
  "street":"Estados Unidos",
  "zone":"Miraflores",
  "city":"La Paz",
  "country":"Bolivia",
  "companyId": 1
}

###

GET http://localhost:8070/v1/driver/history
Accept: application/json
Content-Type: application/json

{
  "driverId": 1
}

###
GET http://localhost:8070/v1/driver/vehicle
Accept: application/json
Content-Type: application/json

{
  "driverId": 1
}

###

GET http://localhost:8070/v1/driver/contact
Accept: application/json

###

PUT http://localhost:8070/v1/driver/3/image
Accept: application/json

###

GET http://localhost:8070/v1/driver/company
Accept: application/json

###

GET http://localhost:8070/v1/driver/sesion
Accept: application/json

###

GET http://192.168.0.18:8070/v1/driver/sesion
Accept: application/json

###

DELETE http://localhost:8070/v1/driver/7
Accept: application/json


