POST http://localhost:8070/v1/driver
Accept: application/json
Content-Type: application/json

{
  "ci": "124248596 lp",
  "firstName": "Jorge",
  "firstSurname": "Mamani",
  "secondSurname": "Quispe",
  "birthDate": "1996-11-10",
  "phone": "+591 68459315",
  "email": "mamani@gmail.com",
  "password": "mamani",
  "number":"198B",
  "street":"Pisagua",
  "zone":"Norte",
  "city":"La Paz",
  "country":"Bolivia"
}

###

GET http://localhost:8070/v1/driver/2
Accept: application/json

###

PUT  http://localhost:8070/v1/driver
Accept: application/json
Content-Type: application/json

{
  "driverId": 1,
  "ci": "124248596 sc",
  "firstName": "Maria",
  "firstSurname": "Sarmiento",
  "secondSurname": "Daza",
  "birthDate": "1974-01-17",
  "phone": "+591 77745812",
  "email": "mariasarmiento@gmail.com",
  "password": "mariasarmiento",
  "number":"198B",
  "street":"Estados Unidos",
  "zone":"Miraflores",
  "city":"La Paz",
  "country":"Bolivia"
}

###

GET http://localhost:8070/v1/driver/history
Accept: application/json
Content-Type: application/json

{
  "driverId": 1
}

###
GET http://localhost:8070/v1/driver/vehicle
Accept: application/json
Content-Type: application/json

{
  "driverId": 1
}

###

GET http://localhost:8070/v1/driver/contact
Accept: application/json
