POST http://localhost:8080/v1/travel
Accept: application/json
Content-Type: application/json

{
  "travelUserId": 7,
  "travelDriverId": 2,
  "travelStatus": "Confirmado",
  "travelDateDelivery": "2020-11-11",
  "addressNumber": "226",
  "addressStreet": "Chulumani",
  "addressZone": "Villa Fatima",
  "addressCity": "La Paz",
  "addressCountry": "Bolivia"

}
