POST http://localhost:8070/v1/travel
Accept: application/json
Content-Type: application/json

{
  "travelUserId": 2,
  "travelDriverId": 1,
  "travelStatus": "Confirmado",
  "travelDateDelivery": "2020-11-11",
  "startAddressNumber": "3226",
  "startAddressStreet": "Calle 4",
  "startAddressZone": "Ramos",
  "startAddressCity": "La Paz",
  "startAddressCountry": "Bolivia",
  "deliveryAddressNumber": "2422",
  "deliveryAddressStreet": "Calle 7",
  "deliveryAddressZone": "Valentino",
  "deliveryAddressCity": "La Paz",
  "deliveryAddressCountry": "Bolivia"

}

###

GET http://localhost:8070/v1/travel/findDriver/1
Accept: application/json
Content-Type: application/json

###