POST http://localhost:8090/v1/user
Accept: application/json
Content-Type: application/json

{
  "ci": "124248596 lp",
  "firstName": "Juan",
  "firstSurname": "Colque",
  "secondSurname": "Mayta",
  "birthDate": "1996-11-10",
  "phone": "+591 68459315",
  "email": "juancolque@gmail.com",
  "password": "juancolque",
  "number":"198B",
  "street":"Pisagua",
  "zone":"Norte",
  "city":"La Paz",
  "country":"Bolivia"
}

###

GET http://localhost:8090/v1/user?userId=2
Accept: application/json

###

PUT  http://localhost:8090/v1/user
Accept: application/json
Content-Type: application/json

{
  
}